version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - mongo # Jika Anda menggunakan database MongoDB, ganti ini sesuai dengan nama layanan MongoDB Anda

  # Jika Anda juga ingin menggunakan database MongoDB dalam container Docker
  # Uncomment bagian ini dan sesuaikan konfigurasi sesuai kebutuhan
  #mongo:
  #  image: mongo
  #  ports:
  #    - "27017:27017"
